[package]
name = "rs_tool"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
gethostname = "0.4.3"
local-ip-address = "0.6.1"
sys-info = "0.9.1"
